image: Visual Studio 2015
configuration: Release
platform:
  - x64
clone_folder: C:\projects\dav1d

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - cd C:\projects
  # Install nasm
  - curl -L -o nasm.zip https://www.nasm.us/pub/nasm/releasebuilds/2.14/win64/nasm-2.14-win64.zip
  - 7z x nasm.zip
  - ps: $env:path="C:\projects\nasm-2.14;$($env:path)"
  # Install ninja
  - mkdir ninja
  - cd ninja
  - curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip
  - 7z x ninja.zip
  - ps: $env:path="C:\projects\ninja;$($env:path)"
  - cd ..
  # Install meson
  - C:\Python36-x64\python.exe -m pip install meson
  - C:\Python36-x64\python.exe -m pip show meson
  - ps: $env:path="C:\python36-x64\lib\site-packages;$($env:path)"
  - dir C:\python36-x64\lib\site-packages

build_script:
  - meson build --buildtype release
  - ninja -C build

after_build:
  # Pack all the files in one direcory and create the zip and installer
